repos:
  - repo: local
    hooks:
      - id: jupytext
        name: jupytext
        entry: poetry run jupytext --sync --pipe black
        language: system
        files: 'md_notebooks/.*\.md'
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
